CREATE TABLE Person (
                        id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
                        username VARCHAR(100) NOT NULL ,
                        year_of_birth int NOT NULL ,
                        password VARCHAR NOT NULL
);